import{auth}from'./auth';const API_URL=(import.meta as any).env?.VITE_API_URL||'http://localhost:3001/api';type Ref={kind:'collection'|'doc';collection:string;id?:string;constraints?:any[]};export const db={};
export const collection=(_db:unknown,name:string):Ref=>({kind:'collection',collection:name});export const doc=(_db:unknown,name:string,id:string):Ref=>({kind:'doc',collection:name,id});export const where=(field:string,op:string,value:unknown)=>({type:'where',field,op,value});export const orderBy=(field:string,direction='asc')=>({type:'orderBy',field,direction});export const limit=(value:number)=>({type:'limit',value});export const query=(ref:Ref,...constraints:any[]):Ref=>({...ref,constraints});export const serverTimestamp=()=>new Date().toISOString();
async function request(path:string,init?:RequestInit){const token=await auth.currentUser?.getIdToken();const response=await fetch(`${API_URL}${path}`,{...init,credentials:'include',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{ }),...init?.headers}});const body=await response.json().catch(()=>({}));if(!response.ok)throw Object.assign(new Error(body.error||`API error ${response.status}`),{code:response.status===403?'permission-denied':'api-error'});return body;}
export const getMemberDistricts=()=>request('/member-lookups/districts');
export const getTraditionalAuthorities=(district:string)=>request(`/member-lookups/traditional-authorities?district=${encodeURIComponent(district)}`);
export const getLoanProducts=()=>request('/loan-products');
export const createLoanProduct=(data:any)=>request('/loan-products',{method:'POST',body:JSON.stringify(data)});
export const updateLoanProduct=(id:string,data:any)=>request(`/loan-products/${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify(data)});
export const estimateLoanApplication=(data:any)=>request('/loan-applications/estimate',{method:'POST',body:JSON.stringify(data)});
export const submitLoanApplication=(data:any)=>request('/loan-applications',{method:'POST',body:JSON.stringify(data)});
export const getApplicationReviews=(filters:Record<string,string>={})=>request(`/application-reviews?${new URLSearchParams(Object.entries(filters).filter(([,value])=>value)).toString()}`);
export const getApplicationReview=(id:string)=>request(`/application-reviews/${encodeURIComponent(id)}`);
export const getApplicationRevalidation=(id:string)=>request(`/application-reviews/${encodeURIComponent(id)}/revalidation`);
export const getRejectionReasons=()=>request('/application-reviews/rejection-reasons');
export const claimApplicationReview=(id:string,data:any)=>request(`/application-reviews/${encodeURIComponent(id)}/claim`,{method:'POST',body:JSON.stringify(data)});
export const approveApplicationReview=(id:string,data:any)=>request(`/application-reviews/${encodeURIComponent(id)}/approve`,{method:'POST',body:JSON.stringify(data)});
export const rejectApplicationReview=(id:string,data:any)=>request(`/application-reviews/${encodeURIComponent(id)}/reject`,{method:'POST',body:JSON.stringify(data)});
export const getLoanDisbursements=(filters:Record<string,string>={})=>request(`/loan-disbursements?${new URLSearchParams(Object.entries(filters).filter(([,value])=>value)).toString()}`);
export const getLoanDisbursement=(applicationId:string)=>request(`/loan-disbursements/${encodeURIComponent(applicationId)}`);
export const recordManualDisbursement=(applicationId:string,data:any)=>request(`/loan-disbursements/${encodeURIComponent(applicationId)}/manual`,{method:'POST',body:JSON.stringify(data)});
export const getRepaymentLoans=(search='')=>request(`/loan-repayments/loans?search=${encodeURIComponent(search)}`);
export const getRepaymentLoan=(loanId:string)=>request(`/loan-repayments/loans/${encodeURIComponent(loanId)}`);
export const getRepaymentHistory=(filters:Record<string,string>={})=>request(`/loan-repayments/history?${new URLSearchParams(Object.entries(filters).filter(([,value])=>value)).toString()}`);
export const getRepaymentReceipt=(repaymentId:string)=>request(`/loan-repayments/receipts/${encodeURIComponent(repaymentId)}`);
export const recordManualRepayment=(loanId:string,data:any)=>request(`/loan-repayments/loans/${encodeURIComponent(loanId)}/manual`,{method:'POST',body:JSON.stringify(data)});
export const getPenaltyPolicies=(search='')=>request(`/penalty-policies?search=${encodeURIComponent(search)}`);
export const getPenaltyPolicy=(id:string)=>request(`/penalty-policies/${encodeURIComponent(id)}`);
export const createPenaltyPolicy=(data:any)=>request('/penalty-policies',{method:'POST',body:JSON.stringify(data)});
export const createPenaltyPolicyVersion=(id:string,data:any)=>request(`/penalty-policies/${encodeURIComponent(id)}/versions`,{method:'POST',body:JSON.stringify(data)});
export const changePenaltyPolicyStatus=(id:string,status:string)=>request(`/penalty-policies/${encodeURIComponent(id)}/status`,{method:'PATCH',body:JSON.stringify({status})});
export const assignPenaltyPolicy=(productId:string,data:any)=>request(`/loan-products/${encodeURIComponent(productId)}/penalty-assignment`,{method:'POST',body:JSON.stringify(data)});
export const previewPenaltyAssessment=(data:any)=>request('/penalty-assessments/preview',{method:'POST',body:JSON.stringify(data)});
export const postPenaltyAssessment=(data:any)=>request('/penalty-assessments/post',{method:'POST',body:JSON.stringify(data)});
export const getPenaltyAssessmentRuns=()=>request('/penalty-assessments/runs');
export const getPenaltyAssessmentCharges=(filters:Record<string,string>={})=>request(`/penalty-assessments/charges?${new URLSearchParams(Object.entries(filters).filter(([,value])=>value)).toString()}`);
export const getPenaltyPaymentLoans=(search='')=>request(`/penalty-payments/loans?search=${encodeURIComponent(search)}`);
export const getPenaltyPaymentLoan=(loanId:string)=>request(`/penalty-payments/loans/${encodeURIComponent(loanId)}`);
export const previewPenaltyPayment=(loanId:string,data:any)=>request(`/penalty-payments/loans/${encodeURIComponent(loanId)}/preview`,{method:'POST',body:JSON.stringify(data)});
export const recordPenaltyPayment=(loanId:string,data:any)=>request(`/penalty-payments/loans/${encodeURIComponent(loanId)}/manual`,{method:'POST',body:JSON.stringify(data)});
export const getPenaltyPaymentHistory=(search='')=>request(`/penalty-payments/history?search=${encodeURIComponent(search)}`);
export const getPenaltyPaymentReceipt=(paymentId:string)=>request(`/penalty-payments/receipts/${encodeURIComponent(paymentId)}`);
export const getCollectionsDueToday=(params:Record<string,string>)=>request(`/collections/due-today?${new URLSearchParams(params)}`);
export const getCollectionsOverdue=(params:Record<string,string>)=>request(`/collections/overdue?${new URLSearchParams(params)}`);
export const getCollectionCases=(params:Record<string,string>={})=>request(`/collections/cases?${new URLSearchParams(params)}`);
export const getCollectionCase=(id:string)=>request(`/collections/cases/${encodeURIComponent(id)}`);
export const getCollectionsStaff=()=>request('/collections/staff');
export const openCollectionCase=(data:any)=>request('/collections/cases',{method:'POST',body:JSON.stringify({...data,notes:data.notes||data.reason})});
export const updateCollectionCaseStatus=(id:string,data:any)=>request(`/collections/cases/${encodeURIComponent(id)}/status`,{method:'PATCH',body:JSON.stringify(data)});
export const assignCollectionCase=(id:string,data:any)=>request(`/collections/cases/${encodeURIComponent(id)}/assign`,{method:'POST',body:JSON.stringify(data)});
export const addCollectionAction=(id:string,data:any)=>request(`/collections/cases/${encodeURIComponent(id)}/actions`,{method:'POST',body:JSON.stringify(data)});
const snapshotDoc=(value:any)=>({id:value.id,exists:()=>Boolean(value),data:()=>{const{id,...data}=value;return data;}});function apply(rows:any[],constraints:any[]=[]){let result=[...rows];for(const c of constraints){if(c.type==='where'&&c.op==='==')result=result.filter(r=>r[c.field]===c.value);if(c.type==='orderBy')result.sort((a,b)=>String(a[c.field]||'').localeCompare(String(b[c.field]||''))*(c.direction==='desc'?-1:1));if(c.type==='limit')result=result.slice(0,c.value);}return result;}
export async function getDoc(ref:Ref){try{return snapshotDoc(await request(`/${ref.collection}/${ref.id}`));}catch(e:any){if(e.message==='Not found')return{id:ref.id,exists:()=>false,data:()=>undefined};throw e;}}export const getDocFromServer=getDoc;export async function getDocs(ref:Ref){const rows=apply(await request(`/${ref.collection}?limit=250`),ref.constraints);return{empty:rows.length===0,docs:rows.map(snapshotDoc)}}export async function setDoc(ref:Ref,data:any,options?:{merge?:boolean}){return request(`/${ref.collection}/${ref.id}`,{method:options?.merge?'PATCH':'PUT',body:JSON.stringify(data)})}export async function updateDoc(ref:Ref,data:any){return request(`/${ref.collection}/${ref.id}`,{method:'PATCH',body:JSON.stringify(data)})}export async function addDoc(ref:Ref,data:any){const value=await request(`/${ref.collection}`,{method:'POST',body:JSON.stringify(data)});return{id:value.id}}export function onSnapshot(ref:Ref,success:(s:any)=>void,failure:(e:any)=>void=console.error){let active=true;const load=async()=>{try{success(ref.kind==='doc'?await getDoc(ref):await getDocs(ref));}catch(e){failure(e)}};load();const timer=window.setInterval(()=>active&&load(),5000);return()=>{active=false;clearInterval(timer)}}
