import assert from 'node:assert/strict';
import test from 'node:test';
import { assertMakerChecker, assertTransition, calculateApprovedTerms, canReadReviews, canReviewApplications, revalidateExternalLoan, validateApprovalInput, validateRejectionInput } from './application-review.js';
import type { ApplicationProduct } from './loan-application.js';
import type { FeeConfiguration } from './loan-product.js';

const fee = (overrides: Partial<FeeConfiguration> = {}): FeeConfiguration => ({ enabled: false, type: 'PERCENTAGE', fixedMinor: 0, percentageBps: 0, calculationBase: 'REQUESTED', chargeTiming: 'ONCE', vatEnabled: false, ...overrides });
const product = (overrides: Partial<ApplicationProduct> = {}): ApplicationProduct => ({ id: 'p1', version: 3, productCode: 'REV', productName: 'Review', minAmountMinor: 100_000, maxAmountMinor: 500_000, annualInterestRateBps: 1200, interestMethod: 'FLAT_RATE', repaymentFrequency: 'MONTHLY', minPeriods: 6, maxPeriods: 24, insuranceFee: fee({ enabled: true, percentageBps: 100, vatEnabled: true }), administrationFee: fee({ enabled: true, type: 'FIXED', fixedMinor: 2_000, calculationBase: 'APPROVED' }), vatRateBps: 1650, externalLoanRepaymentThresholdBps: 7000, status: 'ACTIVE', effectiveDate: '2026-01-01', ...overrides });
const application = { requested_amount_minor: 200_000, has_external_loan: 0, external_original_amount_minor: null, external_repaid_minor: null };

test('permits only the controlled review transitions', () => { assert.doesNotThrow(() => assertTransition('SUBMITTED', 'UNDER_REVIEW')); assert.doesNotThrow(() => assertTransition('UNDER_REVIEW', 'APPROVED')); assert.throws(() => assertTransition('APPROVED', 'UNDER_REVIEW'), /Invalid/); assert.throws(() => assertTransition('REJECTED', 'APPROVED'), /Invalid/); });
test('enforces maker-checker and role permissions', () => { assert.throws(() => assertMakerChecker('same', 'same'), /Maker-checker/); assert.doesNotThrow(() => assertMakerChecker('maker', 'checker')); assert.equal(canReviewApplications('ADMIN'), true); assert.equal(canReviewApplications('OFFICER'), true); assert.equal(canReviewApplications('AUDITOR'), false); assert.equal(canReviewApplications('AGENT'), false); assert.equal(canReadReviews('AUDITOR'), true); });
test('validates approval confirmation and optimistic-lock inputs', () => { const valid = { approvedAmountMinor: 150_000, approvedRepaymentPeriods: 12, approvalNotes: 'Capacity verified', confirmedFrequency: 'MONTHLY', confirmedInterestMethod: 'FLAT_RATE', confirmedAnnualRateBps: 1200, confirmFeesAndVat: true, explicitConfirmation: true, expectedVersion: 2, idempotencyKey: '00000000-0000-4000-8000-000000000001' }; assert.equal(validateApprovalInput(valid).expectedVersion, 2); assert.throws(() => validateApprovalInput({ ...valid, expectedVersion: 0 }), /Expected review version/); });
test('requires a configured rejection reason, explanation and confirmation', () => { const base = { reviewerNotes: 'Verified reason', explicitConfirmation: true, expectedVersion: 2, idempotencyKey: '00000000-0000-4000-8000-000000000002' }; assert.equal(validateRejectionInput(base, { code: 'CAPACITY', requiresExplanation: false }).reasonCode, 'CAPACITY'); assert.throws(() => validateRejectionInput(base, undefined), /valid rejection reason/); assert.throws(() => validateRejectionInput({ ...base, reviewerNotes: '' }, { code: 'OTHER', requiresExplanation: true }), /required/); assert.throws(() => validateRejectionInput({ ...base, explicitConfirmation: false }, { code: 'CAPACITY', requiresExplanation: false }), /confirmation/); });
test('calculates and snapshots approved terms without floating-point money', () => { const terms = calculateApprovedTerms(application, product(), 150_000, 12); assert.equal(terms.interestMinor, 18_000); assert.deepEqual(terms.insurance, { feeMinor: 2_000, vatMinor: 330, totalMinor: 2_330 }); assert.equal(terms.administration.totalMinor, 2_000); assert.equal(terms.estimatedTotalMinor, 172_330); assert.throws(() => calculateApprovedTerms(application, product(), 200_001, 12), /requested/); assert.throws(() => calculateApprovedTerms(application, product(), 150_000, 25), /period/); });
test('revalidates the external-loan threshold strictly above the configured percentage', () => { const base = { ...application, has_external_loan: 1, external_original_amount_minor: 100_000 }; assert.equal(revalidateExternalLoan({ ...base, external_repaid_minor: 70_000 }, product()).eligible, false); assert.equal(revalidateExternalLoan({ ...base, external_repaid_minor: 70_001 }, product()).eligible, true); });
