import{calculateFeeMinor,calculateFlatRateInterestMinor,calculateReducingBalanceSchedule,type FeeConfiguration}from'./loan-product.js';
import{externalLoanEligibility,type ApplicationProduct}from'./loan-application.js';
export type ReviewStatus='SUBMITTED'|'UNDER_REVIEW'|'APPROVED'|'REJECTED';
export const allowedTransitions:Record<string,ReviewStatus[]>={SUBMITTED:['UNDER_REVIEW','REJECTED'],UNDER_REVIEW:['APPROVED','REJECTED'],APPROVED:[],REJECTED:[]};
export function assertTransition(from:string,to:ReviewStatus){if(!allowedTransitions[from]?.includes(to))throw new Error(`Invalid application status transition from ${from} to ${to}.`);}
const integer=(value:unknown,name:string,min=0)=>{const parsed=Number(value);if(!Number.isSafeInteger(parsed)||parsed<min)throw new Error(`${name} must be a whole number of at least ${min}.`);return parsed;};
const text=(value:unknown,name:string,max=5000)=>{const parsed=String(value??'').trim();if(!parsed)throw new Error(`${name} is required.`);if(parsed.length>max)throw new Error(`${name} must not exceed ${max} characters.`);return parsed;};
export const validIdempotencyKey=(value:unknown)=>{const key=text(value,'Idempotency key',36);if(!/^[0-9a-f-]{36}$/i.test(key))throw new Error('Idempotency key is invalid.');return key;};
export function validateApprovalInput(input:any){return{approvedAmountMinor:integer(input?.approvedAmountMinor,'Approved amount',1),approvedRepaymentPeriods:integer(input?.approvedRepaymentPeriods,'Approved repayment period',1),approvalNotes:text(input?.approvalNotes,'Approval notes'),confirmedFrequency:text(input?.confirmedFrequency,'Repayment frequency',32),confirmedInterestMethod:text(input?.confirmedInterestMethod,'Interest method',32),confirmedAnnualRateBps:integer(input?.confirmedAnnualRateBps,'Annual interest rate'),confirmFeesAndVat:input?.confirmFeesAndVat===true,explicitConfirmation:input?.explicitConfirmation===true,expectedVersion:integer(input?.expectedVersion,'Expected review version',1),idempotencyKey:validIdempotencyKey(input?.idempotencyKey)};}
export function validateRejectionInput(input:any,reason:{code:string;requiresExplanation:boolean}|undefined){if(!reason)throw new Error('Select a valid rejection reason.');const notes=text(input?.reviewerNotes,'Reviewer explanation');if(reason.requiresExplanation&&!notes)throw new Error('An explanation is required for Other.');if(input?.explicitConfirmation!==true)throw new Error('Explicit rejection confirmation is required.');return{reasonCode:reason.code,reviewerNotes:notes,expectedVersion:integer(input?.expectedVersion,'Expected review version',1),idempotencyKey:validIdempotencyKey(input?.idempotencyKey)};}
const exactRoundDiv=(n:bigint,d:bigint)=>Number((n+d/2n)/d);
const periodsPerYear={WEEKLY:52,FORTNIGHTLY:26,MONTHLY:12,QUARTERLY:4}as const;
export function calculateApprovedTerms(application:any,product:ApplicationProduct,approvedAmountMinor:number,approvedPeriods:number){if(approvedAmountMinor>Number(application.requested_amount_minor))throw new Error('Approved amount cannot exceed the requested amount.');if(approvedAmountMinor<product.minAmountMinor||approvedAmountMinor>product.maxAmountMinor)throw new Error('Approved amount is outside the submitted product limits.');if(approvedPeriods<product.minPeriods||approvedPeriods>product.maxPeriods)throw new Error('Approved repayment period is outside the submitted product limits.');const perYear=periodsPerYear[product.repaymentFrequency],interestMinor=product.interestMethod==='FLAT_RATE'?calculateFlatRateInterestMinor(approvedAmountMinor,product.annualInterestRateBps,approvedPeriods,perYear):calculateReducingBalanceSchedule(approvedAmountMinor,product.annualInterestRateBps,approvedPeriods,perYear).reduce((sum,row)=>sum+row.interestMinor,0);const requested=Number(application.requested_amount_minor),insurance=calculateFeeMinor(product.insuranceFee,requested,approvedAmountMinor,product.vatRateBps),administration=calculateFeeMinor(product.administrationFee,requested,approvedAmountMinor,product.vatRateBps),estimatedTotalMinor=approvedAmountMinor+interestMinor+insurance.totalMinor+administration.totalMinor,estimatedInstalmentMinor=exactRoundDiv(BigInt(estimatedTotalMinor),BigInt(approvedPeriods));return{approvedAmountMinor,approvedRepaymentPeriods:approvedPeriods,repaymentFrequency:product.repaymentFrequency,interestMethod:product.interestMethod,annualInterestRateBps:product.annualInterestRateBps,interestMinor,insurance,administration,estimatedTotalMinor,estimatedInstalmentMinor,disbursementStatus:'AWAITING_DISBURSEMENT'};}
export function revalidateExternalLoan(application:any,product:ApplicationProduct){return externalLoanEligibility({hasExternalLoan:Boolean(application.has_external_loan),externalOriginalAmountMinor:application.external_original_amount_minor===null?null:Number(application.external_original_amount_minor),externalRepaidMinor:application.external_repaid_minor===null?null:Number(application.external_repaid_minor)},product.externalLoanRepaymentThresholdBps);}
export const canReviewApplications=(role:string)=>role==='ADMIN'||role==='OFFICER';
export const canReadReviews=(role:string)=>['ADMIN','OFFICER','AUDITOR'].includes(role);
export const assertMakerChecker=(creatorId:string,reviewerId:string)=>{if(creatorId===reviewerId)throw new Error('Maker-checker control prevents the application creator from reviewing their own application.');};
