import{createHash}from'node:crypto';
export const COLLECTION_BUCKETS=[{key:'DUE_TODAY',label:'Current / Due Today',min:0,max:0},{key:'1_7',label:'1–7 days',min:1,max:7},{key:'8_30',label:'8–30 days',min:8,max:30},{key:'31_60',label:'31–60 days',min:31,max:60},{key:'61_90',label:'61–90 days',min:61,max:90},{key:'90_PLUS',label:'More than 90 days',min:91,max:Infinity}]as const;
const validDate=(v:any,n='Business date')=>{const s=String(v||'');if(!/^\d{4}-\d{2}-\d{2}$/.test(s)||Number.isNaN(Date.parse(`${s}T00:00:00Z`)))throw new Error(`${n} is invalid.`);return s};const days=(a:string,b:string)=>Math.floor((Date.parse(`${b}T00:00:00Z`)-Date.parse(`${a}T00:00:00Z`))/86400000);
export function classifyInstalment(row:{dueDate:string;totalDueMinor:number;totalPaidMinor:number},businessDate:string){validDate(businessDate);if(row.totalPaidMinor>=row.totalDueMinor)return'SETTLED';return row.dueDate===businessDate?'DUE_TODAY':row.dueDate<businessDate?'OVERDUE':'UPCOMING'}
export const delinquencyBucket=(dpd:number)=>COLLECTION_BUCKETS.find(b=>dpd>=b.min&&dpd<=b.max)?.key||'DUE_TODAY';
export function summarizeDelinquency(rows:any[],businessDate:string){const unpaid=rows.filter(r=>classifyInstalment(r,businessDate)!=='SETTLED'),overdue=unpaid.filter(r=>r.dueDate<businessDate).sort((a,b)=>a.dueDate.localeCompare(b.dueDate)||a.instalmentNumber-b.instalmentNumber),oldest=overdue[0];return{daysPastDue:oldest?days(oldest.dueDate,businessDate):0,bucket:delinquencyBucket(oldest?days(oldest.dueDate,businessDate):0),overdueCount:overdue.length,oldestUnpaidDueDate:oldest?.dueDate||null}}
export const canViewCollections=(r:string)=>['ADMIN','OFFICER','AUDITOR'].includes(r);export const canWorkCollections=(r:string)=>['ADMIN','OFFICER'].includes(r);export const canAssignCollections=(r:string)=>r==='ADMIN';
const text=(v:any,n:string,max:number)=>{const s=String(v??'').trim();if(!s)throw new Error(`${n} is required.`);if(s.length>max)throw new Error(`${n} is too long.`);return s};const integer=(v:any,n:string,min=0)=>{const x=Number(v);if(!Number.isSafeInteger(x)||x<min)throw new Error(`${n} is invalid.`);return x};
export const CASE_TRANSITIONS:any={OPEN:['IN_PROGRESS','PROMISE_TO_PAY','MONITORING','RESOLVED','CLOSED'],IN_PROGRESS:['PROMISE_TO_PAY','MONITORING','RESOLVED','CLOSED'],PROMISE_TO_PAY:['IN_PROGRESS','MONITORING','RESOLVED','CLOSED'],MONITORING:['IN_PROGRESS','PROMISE_TO_PAY','RESOLVED','CLOSED'],RESOLVED:['OPEN'],CLOSED:['OPEN']};export function assertCaseTransition(from:string,to:string,reason:any){if(!CASE_TRANSITIONS[from]?.includes(to))throw new Error(`Invalid collection case transition from ${from} to ${to}.`);const r=text(reason,'Transition reason',1000);if(['RESOLVED','CLOSED'].includes(to)&&!r)throw new Error('Resolution reason is required.');return r}
export function validateAction(v:any){const actionType=String(v?.actionType||''),types=['PHONE_CALL','SMS_MANUAL','EMAIL_MANUAL','IN_PERSON_VISIT','LETTER','MEMBER_CONTACTED','NEXT_OF_KIN_CONTACTED','PROMISE_TO_PAY','NO_ANSWER','WRONG_CONTACT_DETAILS','FOLLOW_UP_SCHEDULED','OTHER'];if(!types.includes(actionType))throw new Error('Action type is invalid.');const actionAt=String(v?.actionAt||'');if(Number.isNaN(Date.parse(actionAt)))throw new Error('Action date and time is invalid.');const idempotencyKey=text(v?.idempotencyKey,'Idempotency key',36);if(!/^[0-9a-f-]{36}$/i.test(idempotencyKey))throw new Error('Idempotency key is invalid.');const promise=actionType==='PROMISE_TO_PAY'?{promisedAmountMinor:integer(v?.promise?.promisedAmountMinor,'Promised amount',1),promisedPaymentDate:validDate(v?.promise?.promisedPaymentDate,'Promised payment date'),statedMethod:String(v?.promise?.statedMethod||'').slice(0,64),notes:text(v?.promise?.notes,'Promise notes',5000)}:null;return{actionType,actionAt,outcome:text(v?.outcome,'Outcome',500),notes:text(v?.notes,'Action notes',5000),nextFollowUpDate:v?.nextFollowUpDate?validDate(v.nextFollowUpDate,'Next follow-up date'):null,idempotencyKey,promise}}
export const actionHash=(v:ReturnType<typeof validateAction>)=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
