import { createHash } from 'node:crypto';
export type RepaymentMethod='BANK_TRANSFER'|'MOBILE_MONEY'|'CASH'|'CHEQUE'|'OTHER_MANUAL';
const integer=(value:unknown,name:string,min=0)=>{const n=Number(value);if(!Number.isSafeInteger(n)||n<min)throw new Error(`${name} must be a whole number of at least ${min}.`);return n;};
const text=(value:unknown,name:string,max:number)=>{const v=String(value??'').trim();if(!v)throw new Error(`${name} is required.`);if(v.length>max)throw new Error(`${name} must not exceed ${max} characters.`);return v;};
export const canViewRepayments=(role:string)=>['ADMIN','OFFICER','AUDITOR'].includes(role);
export const canRecordRepayments=(role:string)=>['ADMIN','OFFICER'].includes(role);
export function validateRepaymentInput(input:any){const method=String(input?.method)as RepaymentMethod;if(!['BANK_TRANSFER','MOBILE_MONEY','CASH','CHEQUE','OTHER_MANUAL'].includes(method))throw new Error('Repayment method is invalid.');const paymentDate=String(input?.paymentDate||'');if(!/^\d{4}-\d{2}-\d{2}$/.test(paymentDate)||Number.isNaN(Date.parse(`${paymentDate}T00:00:00Z`)))throw new Error('Payment date is invalid.');if(input?.externalPaymentConfirmed!==true)throw new Error('Confirm that the payment was completed outside the system.');const idempotencyKey=text(input?.idempotencyKey,'Idempotency key',36);if(!/^[0-9a-f-]{36}$/i.test(idempotencyKey))throw new Error('Idempotency key is invalid.');return{paymentDate,amountMinor:integer(input?.amountMinor,'Payment amount',1),method,externalReference:text(input?.externalReference,'External payment reference',128),notes:text(input?.notes,'Repayment notes',5000),expectedVersion:integer(input?.expectedVersion,'Expected loan version',1),idempotencyKey};}
export const repaymentRequestHash=(input:ReturnType<typeof validateRepaymentInput>)=>createHash('sha256').update(JSON.stringify(input)).digest('hex');
export type ScheduleBalance={id:number;instalmentNumber:number;dueDate:string;principalDueMinor:number;principalPaidMinor:number;interestDueMinor:number;interestPaidMinor:number;feeDueMinor:number;feePaidMinor:number;vatDueMinor:number;vatPaidMinor:number;totalDueMinor:number;totalPaidMinor:number};
export function allocateRepayment(rows:ScheduleBalance[],amountMinor:number,paymentDate:string){const amount=BigInt(integer(amountMinor,'Payment amount',1)),eligible=rows.filter(row=>row.dueDate<=paymentDate).sort((a,b)=>a.dueDate.localeCompare(b.dueDate)||a.instalmentNumber-b.instalmentNumber);const due=eligible.reduce((sum,row)=>sum+BigInt(row.totalDueMinor-row.totalPaidMinor),0n);if(due<=0n)throw new Error('No contractual instalment is due on or before the payment date. Future prepayment is not configured.');if(amount>due)throw new Error(`Payment exceeds the due-and-unpaid amount. Maximum acceptable amount is ${due} minor units; future prepayment and unapplied credit are not configured.`);let remaining=amount;const allocations:any[]=[];for(const row of eligible){if(remaining===0n)break;const allocation={scheduleId:row.id,instalmentNumber:row.instalmentNumber,vatMinor:0,feeMinor:0,interestMinor:0,principalMinor:0,totalMinor:0};for(const [dueKey,paidKey,outKey] of [['vatDueMinor','vatPaidMinor','vatMinor'],['feeDueMinor','feePaidMinor','feeMinor'],['interestDueMinor','interestPaidMinor','interestMinor'],['principalDueMinor','principalPaidMinor','principalMinor']] as const){const outstanding=BigInt(row[dueKey]-row[paidKey]);if(outstanding<0n)throw new Error(`Instalment ${row.instalmentNumber} has a negative component balance.`);const applied=remaining<outstanding?remaining:outstanding;allocation[outKey]=Number(applied);remaining-=applied;}allocation.totalMinor=allocation.vatMinor+allocation.feeMinor+allocation.interestMinor+allocation.principalMinor;if(allocation.totalMinor)allocations.push(allocation);}if(remaining!==0n||allocations.reduce((sum,row)=>sum+BigInt(row.totalMinor),0n)!==amount)throw new Error('Repayment allocation did not reconcile exactly.');return allocations;}
