export type LoanProductRole='ADMIN'|'OFFICER'|'AGENT'|'AUDITOR';
export type FeeConfiguration={enabled:boolean;type:'FIXED'|'PERCENTAGE';fixedMinor:number;percentageBps:number;calculationBase:'REQUESTED'|'APPROVED';chargeTiming:'ONCE'|'PERIODIC';vatEnabled:boolean};
export type LoanProductInput={productName:string;productCode:string;description:string;minAmountMinor:number;maxAmountMinor:number;annualInterestRateBps:number;interestMethod:'FLAT_RATE'|'REDUCING_BALANCE';repaymentFrequency:'WEEKLY'|'FORTNIGHTLY'|'MONTHLY'|'QUARTERLY';minPeriods:number;maxPeriods:number;insuranceFee:FeeConfiguration;administrationFee:FeeConfiguration;vatRateBps:number;penaltyConfigurationReference:string|null;gracePeriodDays:number;externalLoanRepaymentThresholdBps:number;status:'ACTIVE'|'INACTIVE'|'ARCHIVED';effectiveDate:string};

const integer=(value:unknown,name:string,min=0,max=Number.MAX_SAFE_INTEGER)=>{const parsed=Number(value);if(!Number.isSafeInteger(parsed)||parsed<min||parsed>max)throw new Error(`${name} must be a whole number between ${min} and ${max}.`);return parsed;};
const text=(value:unknown,name:string,max:number)=>{const parsed=String(value??'').trim();if(!parsed)throw new Error(`${name} is required.`);if(parsed.length>max)throw new Error(`${name} must not exceed ${max} characters.`);return parsed;};
const choice=<T extends string>(value:unknown,name:string,values:readonly T[])=>{if(!values.includes(value as T))throw new Error(`${name} is invalid.`);return value as T;};
const fee=(value:any,name:string):FeeConfiguration=>{const result={enabled:Boolean(value?.enabled),type:choice(value?.type,`${name} fee type`,['FIXED','PERCENTAGE']as const),fixedMinor:integer(value?.fixedMinor??0,`${name} fixed amount`),percentageBps:integer(value?.percentageBps??0,`${name} percentage`,0,10000),calculationBase:choice(value?.calculationBase,`${name} calculation base`,['REQUESTED','APPROVED']as const),chargeTiming:choice(value?.chargeTiming,`${name} charge timing`,['ONCE','PERIODIC']as const),vatEnabled:Boolean(value?.vatEnabled)};if(result.enabled&&result.type==='FIXED'&&result.fixedMinor<=0)throw new Error(`${name} fixed amount must be greater than zero.`);if(result.enabled&&result.type==='PERCENTAGE'&&result.percentageBps<=0)throw new Error(`${name} percentage must be greater than zero.`);return result;};
export function validateLoanProduct(input:any):LoanProductInput{const minAmountMinor=integer(input?.minAmountMinor,'Minimum loan amount',1);const maxAmountMinor=integer(input?.maxAmountMinor,'Maximum loan amount',1);if(minAmountMinor>maxAmountMinor)throw new Error('Minimum loan amount must not exceed maximum loan amount.');const minPeriods=integer(input?.minPeriods,'Minimum repayment period',1,1200);const maxPeriods=integer(input?.maxPeriods,'Maximum repayment period',1,1200);if(minPeriods>maxPeriods)throw new Error('Minimum repayment period must not exceed maximum repayment period.');const effectiveDate=String(input?.effectiveDate??'');if(!/^\d{4}-\d{2}-\d{2}$/.test(effectiveDate)||Number.isNaN(Date.parse(`${effectiveDate}T00:00:00Z`)))throw new Error('Effective date is invalid.');return{productName:text(input?.productName,'Product name',120),productCode:text(input?.productCode,'Product code',40).toUpperCase().replace(/\s+/g,'-'),description:text(input?.description,'Description',5000),minAmountMinor,maxAmountMinor,annualInterestRateBps:integer(input?.annualInterestRateBps,'Annual interest rate',0,10000),interestMethod:choice(input?.interestMethod,'Interest calculation method',['FLAT_RATE','REDUCING_BALANCE']as const),repaymentFrequency:choice(input?.repaymentFrequency,'Repayment frequency',['WEEKLY','FORTNIGHTLY','MONTHLY','QUARTERLY']as const),minPeriods,maxPeriods,insuranceFee:fee(input?.insuranceFee,'Insurance'),administrationFee:fee(input?.administrationFee,'Administration'),vatRateBps:integer(input?.vatRateBps??1650,'VAT rate',0,10000),penaltyConfigurationReference:String(input?.penaltyConfigurationReference??'').trim().slice(0,128)||null,gracePeriodDays:integer(input?.gracePeriodDays??0,'Grace period',0,3650),externalLoanRepaymentThresholdBps:integer(input?.externalLoanRepaymentThresholdBps??7000,'External-loan repayment threshold',0,9999),status:choice(input?.status,'Product status',['ACTIVE','INACTIVE','ARCHIVED']as const),effectiveDate};}
export const canManageLoanProducts=(role:LoanProductRole)=>role==='ADMIN';
export const canViewLoanProducts=(role:LoanProductRole)=>['ADMIN','OFFICER','AUDITOR'].includes(role);
export const isExternalLoanEligible=(repaidPercentageBps:number,thresholdBps=7000)=>integer(repaidPercentageBps,'Repaid percentage',0,10000)>integer(thresholdBps,'Eligibility threshold',0,9999);
const exactRoundDiv=(numerator:bigint,denominator:bigint)=>{const value=(numerator+denominator/2n)/denominator;if(value>BigInt(Number.MAX_SAFE_INTEGER))throw new Error('Calculated monetary value exceeds the supported range.');return Number(value);};
export const calculateFlatRateInterestMinor=(principalMinor:number,annualRateBps:number,periods:number,periodsPerYear=12)=>exactRoundDiv(BigInt(integer(principalMinor,'Principal',0))*BigInt(integer(annualRateBps,'Annual rate',0,10000))*BigInt(integer(periods,'Term',0)),BigInt(10000*integer(periodsPerYear,'Periods per year',1)));
export function calculateReducingBalanceSchedule(principalMinor:number,annualRateBps:number,periods:number,periodsPerYear=12){const principal=integer(principalMinor,'Principal',1),rate=integer(annualRateBps,'Annual rate',0,10000),count=integer(periods,'Term',1,1200),principalPart=Math.floor(principal/count);let balance=principal;return Array.from({length:count},(_,index)=>{const principalDue=index===count-1?balance:principalPart;const interestMinor=exactRoundDiv(BigInt(balance)*BigInt(rate),BigInt(10000*integer(periodsPerYear,'Periods per year',1)));balance-=principalDue;return{period:index+1,principalMinor:principalDue,interestMinor,paymentMinor:principalDue+interestMinor,balanceMinor:balance};});}
export function calculateFeeMinor(config:FeeConfiguration,requestedMinor:number,approvedMinor:number,vatRateBps:number){if(!config.enabled)return{feeMinor:0,vatMinor:0,totalMinor:0};const base=config.calculationBase==='REQUESTED'?integer(requestedMinor,'Requested amount',0):integer(approvedMinor,'Approved amount',0);const feeMinor=config.type==='FIXED'?integer(config.fixedMinor,'Fixed fee',0):exactRoundDiv(BigInt(base)*BigInt(integer(config.percentageBps,'Fee percentage',0,10000)),10000n);const vatMinor=config.vatEnabled?exactRoundDiv(BigInt(feeMinor)*BigInt(integer(vatRateBps,'VAT rate',0,10000)),10000n):0;return{feeMinor,vatMinor,totalMinor:feeMinor+vatMinor};}
