import{calculateFeeMinor,calculateFlatRateInterestMinor,calculateReducingBalanceSchedule,type FeeConfiguration}from'./loan-product.js';
export type ApplicationProduct={id:string;version:number;productCode:string;productName:string;minAmountMinor:number;maxAmountMinor:number;annualInterestRateBps:number;interestMethod:'FLAT_RATE'|'REDUCING_BALANCE';repaymentFrequency:'WEEKLY'|'FORTNIGHTLY'|'MONTHLY'|'QUARTERLY';minPeriods:number;maxPeriods:number;insuranceFee:FeeConfiguration;administrationFee:FeeConfiguration;vatRateBps:number;externalLoanRepaymentThresholdBps:number;status:string;effectiveDate:string};
export type ApplicationInput={memberId:string;productId:string;requestedAmountMinor:number;repaymentPeriods:number;purpose:string;applicantIncomeMinor:number;financialObligationsMinor:number;hasExternalLoan:boolean;externalLender:string|null;externalOriginalAmountMinor:number|null;externalOutstandingMinor:number|null;externalRepaidMinor:number|null;supportingNotes:string|null;documents:Record<string,string>;idempotencyKey:string};
const integer=(value:unknown,name:string,min=0)=>{const parsed=Number(value);if(!Number.isSafeInteger(parsed)||parsed<min)throw new Error(`${name} must be a whole minor-unit amount of at least ${min}.`);return parsed;};
const optionalMoney=(value:unknown,name:string)=>value===null||value===undefined||value===''?null:integer(value,name);
const required=(value:unknown,name:string,max:number)=>{const text=String(value??'').trim();if(!text)throw new Error(`${name} is required.`);if(text.length>max)throw new Error(`${name} must not exceed ${max} characters.`);return text;};
export function validateApplicationInput(input:any):ApplicationInput{const hasExternalLoan=Boolean(input?.hasExternalLoan),externalLender=String(input?.externalLender??'').trim()||null,externalOriginalAmountMinor=optionalMoney(input?.externalOriginalAmountMinor,'Original external-loan amount'),externalOutstandingMinor=optionalMoney(input?.externalOutstandingMinor,'External outstanding balance'),externalRepaidMinor=optionalMoney(input?.externalRepaidMinor,'External amount repaid');if(hasExternalLoan){if(!externalLender)throw new Error('External lender is required.');if(!externalOriginalAmountMinor)throw new Error('Original external-loan amount must be greater than zero.');if(externalOutstandingMinor===null||externalRepaidMinor===null)throw new Error('External outstanding and repaid amounts are required.');if(externalOutstandingMinor>externalOriginalAmountMinor)throw new Error('External outstanding balance cannot exceed the original amount.');if(externalRepaidMinor>externalOriginalAmountMinor)throw new Error('External amount repaid cannot exceed the original amount.');}const idempotencyKey=required(input?.idempotencyKey,'Submission key',36);if(!/^[0-9a-f-]{36}$/i.test(idempotencyKey))throw new Error('Submission key is invalid.');return{memberId:required(input?.memberId,'Member',128),productId:required(input?.productId,'Loan product',36),requestedAmountMinor:integer(input?.requestedAmountMinor,'Requested amount',1),repaymentPeriods:integer(input?.repaymentPeriods,'Repayment period',1),purpose:required(input?.purpose,'Loan purpose',1000),applicantIncomeMinor:integer(input?.applicantIncomeMinor,'Applicant income',1),financialObligationsMinor:integer(input?.financialObligationsMinor??0,'Financial obligations'),hasExternalLoan,externalLender:hasExternalLoan?externalLender:null,externalOriginalAmountMinor:hasExternalLoan?externalOriginalAmountMinor:null,externalOutstandingMinor:hasExternalLoan?externalOutstandingMinor:null,externalRepaidMinor:hasExternalLoan?externalRepaidMinor:null,supportingNotes:String(input?.supportingNotes??'').trim().slice(0,5000)||null,documents:typeof input?.documents==='object'&&input.documents?input.documents:{},idempotencyKey};}
export function externalLoanEligibility(input:Pick<ApplicationInput,'hasExternalLoan'|'externalOriginalAmountMinor'|'externalRepaidMinor'>,thresholdBps:number){if(!input.hasExternalLoan)return{eligible:true,repaymentPercentageBps:null,reason:null};const original=BigInt(input.externalOriginalAmountMinor!),repaid=BigInt(input.externalRepaidMinor!);if(original<=0n)throw new Error('Original external-loan amount must be greater than zero.');const threshold=BigInt(thresholdBps);const repaymentPercentageBps=Number((repaid*10000n+original/2n)/original);const eligible=repaid*10000n>original*threshold;return{eligible,repaymentPercentageBps,reason:eligible?null:`The existing external loan has been repaid by ${(repaymentPercentageBps/100).toFixed(2)}%. More than ${(thresholdBps/100).toFixed(2)}% must be repaid before another application can be submitted.`};}
export function validateProductTerms(input:ApplicationInput,product:ApplicationProduct,today=new Date().toISOString().slice(0,10)){if(product.status!=='ACTIVE')throw new Error('The selected loan product is not active.');if(product.effectiveDate>today)throw new Error('The selected loan product is not yet effective.');if(input.requestedAmountMinor<product.minAmountMinor||input.requestedAmountMinor>product.maxAmountMinor)throw new Error(`Requested amount must be between ${product.minAmountMinor} and ${product.maxAmountMinor} minor units.`);if(input.repaymentPeriods<product.minPeriods||input.repaymentPeriods>product.maxPeriods)throw new Error(`Repayment period must be between ${product.minPeriods} and ${product.maxPeriods}.`);}
const periodsPerYear={WEEKLY:52,FORTNIGHTLY:26,MONTHLY:12,QUARTERLY:4}as const;
export function calculateApplicationEstimate(input:ApplicationInput,product:ApplicationProduct){const perYear=periodsPerYear[product.repaymentFrequency];let interestMinor:number;if(product.interestMethod==='FLAT_RATE')interestMinor=calculateFlatRateInterestMinor(input.requestedAmountMinor,product.annualInterestRateBps,input.repaymentPeriods,perYear);else interestMinor=calculateReducingBalanceSchedule(input.requestedAmountMinor,product.annualInterestRateBps,input.repaymentPeriods,perYear).reduce((sum,row)=>sum+row.interestMinor,0);const insurance=calculateFeeMinor(product.insuranceFee,input.requestedAmountMinor,input.requestedAmountMinor,product.vatRateBps),administration=calculateFeeMinor(product.administrationFee,input.requestedAmountMinor,input.requestedAmountMinor,product.vatRateBps);return{interestMinor,insurance:{...insurance,provisional:product.insuranceFee.calculationBase==='APPROVED'},administration:{...administration,provisional:product.administrationFee.calculationBase==='APPROVED'},estimatedTotalMinor:input.requestedAmountMinor+interestMinor+insurance.totalMinor+administration.totalMinor};}
export const canCreateApplication=(role:string)=>role==='ADMIN'||role==='OFFICER'||role==='AGENT';
export const canViewApplication=(role:string)=>['ADMIN','OFFICER','AUDITOR'].includes(role);
