import assert from 'node:assert/strict';
import test from 'node:test';
import { assertDisbursementMakerChecker, canDisburse, canViewDisbursements, disbursementRequestHash, generateRepaymentSchedule, validateDisbursementInput } from './loan-disbursement.js';

const terms=(overrides:any={})=>({approvedAmountMinor:120000,approvedRepaymentPeriods:12,repaymentFrequency:'MONTHLY',interestMethod:'FLAT_RATE',annualInterestRateBps:1200,interestMinor:14400,insurance:{feeMinor:1000,vatMinor:165,totalMinor:1165},administration:{feeMinor:2000,vatMinor:0,totalMinor:2000},estimatedTotalMinor:137565,...overrides});
const product=(overrides:any={})=>({gracePeriodDays:7,...overrides});
const input=(overrides:any={})=>validateDisbursementInput({method:'BANK_TRANSFER',disbursementDate:'2026-09-01',destinationDetails:'Member bank account ending 1234',externalReference:'BANK-001',supportingNotes:'Payment verified against receipt.',externalPaymentConfirmed:true,createLoanConfirmed:true,expectedVersion:3,idempotencyKey:'00000000-0000-4000-8000-000000000001',...overrides});

test('validates controlled manual recording and confirmations',()=>{assert.equal(input().method,'BANK_TRANSFER');assert.throws(()=>input({method:'API_TRANSFER'}),/method/);assert.throws(()=>input({externalPaymentConfirmed:false}),/Confirm/);assert.throws(()=>input({externalReference:''}),/reference/);});
test('enforces role and maker-checker controls',()=>{assert.equal(canDisburse('ADMIN'),true);assert.equal(canDisburse('OFFICER'),true);assert.equal(canDisburse('AUDITOR'),false);assert.equal(canDisburse('AGENT'),false);assert.equal(canViewDisbursements('AUDITOR'),true);assert.throws(()=>assertDisbursementMakerChecker('maker','approver','maker'),/creator/);assert.throws(()=>assertDisbursementMakerChecker('maker','approver','approver'),/approving reviewer/);});
test('distinguishes conflicting idempotency payloads deterministically',()=>{assert.equal(disbursementRequestHash(input()),disbursementRequestHash(input()));assert.notEqual(disbursementRequestHash(input()),disbursementRequestHash(input({externalReference:'BANK-002'})));});
test('flat schedule reconciles principal and approved total with final-instalment rounding',()=>{const schedule=generateRepaymentSchedule(terms(),product(),'2026-09-01');assert.equal(schedule.length,12);assert.equal(schedule[0].dueDate,'2026-10-08');assert.equal(schedule.reduce((s,r)=>s+r.principalDueMinor,0),120000);assert.equal(schedule.reduce((s,r)=>s+r.totalDueMinor,0),137565);assert.equal(schedule.at(-1)?.closingPrincipalMinor,0);assert.ok(schedule.every(r=>r.status==='UNPAID'));});
test('supports reducing balance and every configured repayment frequency',()=>{for(const [frequency,periods,firstDue] of [['WEEKLY',4,'2026-09-08'],['FORTNIGHTLY',4,'2026-09-15'],['MONTHLY',4,'2026-10-01'],['QUARTERLY',4,'2026-12-01']] as const){const principal=100000,rate=1200,perYear:any={WEEKLY:52,FORTNIGHTLY:26,MONTHLY:12,QUARTERLY:4};let balance=principal,interest=0;for(let i=0;i<periods;i++){interest+=Number((BigInt(balance)*BigInt(rate)+BigInt(10000*perYear[frequency])/2n)/BigInt(10000*perYear[frequency]));balance-=i===periods-1?balance:Math.floor(principal/periods);}const value=terms({approvedAmountMinor:principal,approvedRepaymentPeriods:periods,repaymentFrequency:frequency,interestMethod:'REDUCING_BALANCE',interestMinor:interest,insurance:{feeMinor:0,vatMinor:0,totalMinor:0},administration:{feeMinor:0,vatMinor:0,totalMinor:0},estimatedTotalMinor:principal+interest});const schedule=generateRepaymentSchedule(value,product({gracePeriodDays:0}),'2026-09-01');assert.equal(schedule[0].dueDate,firstDue);assert.equal(schedule.reduce((s,r)=>s+r.totalDueMinor,0),principal+interest);assert.equal(schedule.reduce((s,r)=>s+r.principalDueMinor,0),principal);}});
test('blocks incomplete or inconsistent approval snapshots',()=>{assert.throws(()=>generateRepaymentSchedule(terms({approvedAmountMinor:0}),product(),'2026-09-01'),/principal/);assert.throws(()=>generateRepaymentSchedule(terms({estimatedTotalMinor:1}),product(),'2026-09-01'),/reconcile/);});
