import { createHash } from 'node:crypto';
import { calculateReducingBalanceSchedule } from './loan-product.js';

export type DisbursementMethod='BANK_TRANSFER'|'MOBILE_MONEY'|'CASH'|'CHEQUE'|'OTHER_MANUAL';
const integer=(value:unknown,name:string,min=0)=>{const n=Number(value);if(!Number.isSafeInteger(n)||n<min)throw new Error(`${name} must be a whole number of at least ${min}.`);return n;};
const text=(value:unknown,name:string,max:number)=>{const v=String(value??'').trim();if(!v)throw new Error(`${name} is required.`);if(v.length>max)throw new Error(`${name} must not exceed ${max} characters.`);return v;};
const date=(value:unknown,name:string)=>{const v=String(value??'');if(!/^\d{4}-\d{2}-\d{2}$/.test(v)||Number.isNaN(Date.parse(`${v}T00:00:00Z`)))throw new Error(`${name} is invalid.`);return v;};
export const canViewDisbursements=(role:string)=>['ADMIN','OFFICER','AUDITOR'].includes(role);
export const canDisburse=(role:string)=>['ADMIN','OFFICER'].includes(role);
export function assertDisbursementMakerChecker(creator:string,approver:string,recorder:string){if(recorder===creator)throw new Error('Maker-checker control prevents the application creator from recording its disbursement.');if(recorder===approver)throw new Error('Maker-checker control prevents the approving reviewer from recording its disbursement.');}
export function validateDisbursementInput(input:any){const method=String(input?.method)as DisbursementMethod;if(!['BANK_TRANSFER','MOBILE_MONEY','CASH','CHEQUE','OTHER_MANUAL'].includes(method))throw new Error('Disbursement method is invalid.');if(input?.externalPaymentConfirmed!==true||input?.createLoanConfirmed!==true)throw new Error('Confirm both the external payment and active-loan creation.');const idempotencyKey=text(input?.idempotencyKey,'Idempotency key',36);if(!/^[0-9a-f-]{36}$/i.test(idempotencyKey))throw new Error('Idempotency key is invalid.');return{method,disbursementDate:date(input?.disbursementDate,'Disbursement date'),destinationDetails:text(input?.destinationDetails,'Destination or beneficiary details',500),externalReference:text(input?.externalReference,'External payment reference',128),supportingNotes:text(input?.supportingNotes,'Supporting notes',5000),evidenceReference:String(input?.evidenceReference??'').trim().slice(0,255)||null,expectedVersion:integer(input?.expectedVersion,'Expected application version',1),idempotencyKey};}
export const disbursementRequestHash=(input:ReturnType<typeof validateDisbursementInput>)=>createHash('sha256').update(JSON.stringify(input)).digest('hex');
const roundDiv=(n:bigint,d:bigint)=>Number((n+d/2n)/d);
const distribute=(total:number,count:number)=>{const base=Math.floor(total/count),remainder=total-base*count;return Array.from({length:count},(_,i)=>base+(i===count-1?remainder:0));};
const addFrequency=(dateValue:string,frequency:string,count:number)=>{const d=new Date(`${dateValue}T00:00:00Z`);if(frequency==='WEEKLY')d.setUTCDate(d.getUTCDate()+7*count);else if(frequency==='FORTNIGHTLY')d.setUTCDate(d.getUTCDate()+14*count);else if(frequency==='MONTHLY'||frequency==='QUARTERLY'){const day=d.getUTCDate(),months=count*(frequency==='QUARTERLY'?3:1);d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+months);const last=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate();d.setUTCDate(Math.min(day,last));}else throw new Error('Approved repayment frequency is unsupported.');return d.toISOString().slice(0,10);};
const allocateCharge=(amount:number,timing:string,count:number)=>timing==='PERIODIC'?distribute(amount,count):[amount,...Array(count-1).fill(0)];
export function generateRepaymentSchedule(terms:any,product:any,disbursementDate:string){const principal=integer(terms?.approvedAmountMinor,'Approved principal',1),periods=integer(terms?.approvedRepaymentPeriods,'Approved repayment periods',1),interestTotal=integer(terms?.interestMinor,'Approved interest'),insuranceFee=integer(terms?.insurance?.feeMinor,'Insurance fee'),administrationFee=integer(terms?.administration?.feeMinor,'Administration fee'),insuranceVat=integer(terms?.insurance?.vatMinor,'Insurance VAT'),administrationVat=integer(terms?.administration?.vatMinor,'Administration VAT'),expected=integer(terms?.estimatedTotalMinor,'Approved total payable',1);const grace=integer(product?.gracePeriodDays??0,'Grace period'),base=new Date(`${date(disbursementDate,'Disbursement date')}T00:00:00Z`);base.setUTCDate(base.getUTCDate()+grace);const start=base.toISOString().slice(0,10),principalParts=distribute(principal,periods),insuranceParts=allocateCharge(insuranceFee,product?.insuranceFee?.chargeTiming,periods),administrationParts=allocateCharge(administrationFee,product?.administrationFee?.chargeTiming,periods),insuranceVatParts=allocateCharge(insuranceVat,product?.insuranceFee?.chargeTiming,periods),administrationVatParts=allocateCharge(administrationVat,product?.administrationFee?.chargeTiming,periods);let interestParts:number[];if(terms.interestMethod==='FLAT_RATE')interestParts=distribute(interestTotal,periods);else{const perYear:any={WEEKLY:52,FORTNIGHTLY:26,MONTHLY:12,QUARTERLY:4};interestParts=calculateReducingBalanceSchedule(principal,integer(terms.annualInterestRateBps,'Annual interest rate'),periods,perYear[terms.repaymentFrequency]).map(row=>row.interestMinor);const difference=interestTotal-interestParts.reduce((a,b)=>a+b,0);interestParts[periods-1]+=difference;}let balance=principal;const schedule=Array.from({length:periods},(_,i)=>{const opening=balance,principalDue=i===periods-1?balance:principalParts[i],feeDue=insuranceParts[i]+administrationParts[i],vatDue=insuranceVatParts[i]+administrationVatParts[i];balance-=principalDue;return{instalmentNumber:i+1,dueDate:addFrequency(start,terms.repaymentFrequency,i+1),openingPrincipalMinor:opening,principalDueMinor:principalDue,interestDueMinor:interestParts[i],feeDueMinor:feeDue,vatDueMinor:vatDue,totalDueMinor:principalDue+interestParts[i]+feeDue+vatDue,closingPrincipalMinor:balance,status:'UNPAID'};});if(schedule.reduce((s,r)=>s+r.totalDueMinor,0)!==expected)throw new Error('Approved totals do not reconcile with the contractual repayment schedule.');return schedule;}
