import{createHash}from'node:crypto';
export type PenaltyPaymentMethod='BANK_TRANSFER'|'MOBILE_MONEY'|'CASH'|'CHEQUE'|'OTHER_MANUAL';
const integer=(v:unknown,n:string,min=0)=>{const x=Number(v);if(!Number.isSafeInteger(x)||x<min)throw new Error(`${n} must be a safe whole number of at least ${min}.`);return x};
const text=(v:unknown,n:string,max:number,required=true)=>{const x=String(v??'').trim();if(required&&!x)throw new Error(`${n} is required.`);if(x.length>max)throw new Error(`${n} must not exceed ${max} characters.`);return x};
export const canViewPenaltyPayments=(role:string)=>['ADMIN','OFFICER','AUDITOR'].includes(role);
export const canRecordPenaltyPayments=(role:string)=>['ADMIN','OFFICER'].includes(role);
export function validatePenaltyPayment(input:any){const method=String(input?.method)as PenaltyPaymentMethod;if(!['BANK_TRANSFER','MOBILE_MONEY','CASH','CHEQUE','OTHER_MANUAL'].includes(method))throw new Error('Payment method is invalid.');const paymentDate=String(input?.paymentDate||'');if(!/^\d{4}-\d{2}-\d{2}$/.test(paymentDate)||Number.isNaN(Date.parse(`${paymentDate}T00:00:00Z`)))throw new Error('Payment date is invalid.');if(input?.externalPaymentConfirmed!==true)throw new Error('Confirm that this payment was completed outside Giant Fluid.');const externalReference=text(input?.externalReference,'External reference',128,false)||null;if(['BANK_TRANSFER','MOBILE_MONEY','CHEQUE'].includes(method)&&!externalReference)throw new Error('External reference is required for this payment method.');const idempotencyKey=text(input?.idempotencyKey,'Idempotency key',36);if(!/^[0-9a-f-]{36}$/i.test(idempotencyKey))throw new Error('Idempotency key is invalid.');return{paymentDate,amountMinor:integer(input?.amountMinor,'Payment amount',1),method,externalReference,notes:text(input?.notes,'Notes',5000),expectedVersion:integer(input?.expectedVersion,'Expected penalty balance version',1),idempotencyKey}}
export const penaltyPaymentHash=(v:ReturnType<typeof validatePenaltyPayment>)=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
export type PenaltyBalance={id:string;loanId:string;assessmentDate:string;createdAt:string;amountMinor:number;paidMinor:number;status:string};
export function allocatePenaltyPayment(rows:PenaltyBalance[],amountMinor:number){let remaining=BigInt(integer(amountMinor,'Payment amount',1));const eligible=rows.filter(r=>r.status==='POSTED'||r.status==='PARTIALLY_PAID').sort((a,b)=>a.assessmentDate.localeCompare(b.assessmentDate)||a.createdAt.localeCompare(b.createdAt)||a.id.localeCompare(b.id));const total=eligible.reduce((s,r)=>s+BigInt(r.amountMinor-r.paidMinor),0n);if(total<=0n)throw new Error('This loan has no outstanding posted penalties.');if(remaining>total)throw new Error(`Payment exceeds penalty outstanding. Maximum acceptable amount is ${total} minor units.`);const allocations:any[]=[];for(const r of eligible){if(!remaining)break;const before=BigInt(r.amountMinor-r.paidMinor);if(before<=0n)continue;const applied=remaining<before?remaining:before,after=before-applied;allocations.push({chargeId:r.id,amountMinor:Number(applied),outstandingBeforeMinor:Number(before),outstandingAfterMinor:Number(after),statusBefore:r.status,statusAfter:after===0n?'PAID':'PARTIALLY_PAID'});remaining-=applied}if(remaining||allocations.reduce((s,a)=>s+BigInt(a.amountMinor),0n)!==BigInt(amountMinor))throw new Error('Penalty allocation did not reconcile exactly.');return allocations}
