CREATE TABLE IF NOT EXISTS loan_applications (
  id CHAR(36) NOT NULL PRIMARY KEY,
  reference_number VARCHAR(32) NOT NULL,
  member_id VARCHAR(128) NOT NULL,
  product_id CHAR(36) NOT NULL,
  product_version INT UNSIGNED NOT NULL,
  requested_amount_minor BIGINT UNSIGNED NOT NULL,
  repayment_periods SMALLINT UNSIGNED NOT NULL,
  repayment_frequency ENUM('WEEKLY','FORTNIGHTLY','MONTHLY','QUARTERLY') NOT NULL,
  purpose VARCHAR(1000) NOT NULL,
  application_date DATE NOT NULL,
  applicant_income_minor BIGINT UNSIGNED NOT NULL,
  financial_obligations_minor BIGINT UNSIGNED NOT NULL DEFAULT 0,
  has_external_loan BOOLEAN NOT NULL DEFAULT FALSE,
  external_lender VARCHAR(160) NULL,
  external_original_amount_minor BIGINT UNSIGNED NULL,
  external_outstanding_minor BIGINT UNSIGNED NULL,
  external_repaid_minor BIGINT UNSIGNED NULL,
  external_repayment_bps INT UNSIGNED NULL,
  eligibility_threshold_bps INT UNSIGNED NOT NULL,
  eligibility_result ENUM('ELIGIBLE','INELIGIBLE') NOT NULL,
  eligibility_reasons JSON NOT NULL,
  internal_loans_snapshot JSON NOT NULL,
  supporting_notes TEXT NULL,
  documents_snapshot JSON NOT NULL,
  product_terms_snapshot JSON NOT NULL,
  calculation_snapshot JSON NOT NULL,
  status ENUM('SUBMITTED','PENDING_ASSESSMENT','IN_REVIEW','APPROVED','REJECTED','WITHDRAWN') NOT NULL DEFAULT 'SUBMITTED',
  pending_dedupe_key VARCHAR(300) NULL,
  idempotency_key CHAR(36) NOT NULL,
  created_by CHAR(36) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_loan_application_reference(reference_number),
  UNIQUE KEY uq_loan_application_idempotency(idempotency_key),
  UNIQUE KEY uq_loan_application_pending(pending_dedupe_key),
  INDEX idx_loan_application_member_status(member_id,status),
  INDEX idx_loan_application_product(product_id,product_version),
  CONSTRAINT fk_loan_application_member FOREIGN KEY(member_id) REFERENCES member_directory(member_id),
  CONSTRAINT fk_loan_application_product FOREIGN KEY(product_id) REFERENCES loan_products(id),
  CONSTRAINT fk_loan_application_product_version FOREIGN KEY(product_id,product_version) REFERENCES loan_product_versions(product_id,version)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS loan_application_status_history (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  application_id CHAR(36) NOT NULL,
  from_status VARCHAR(32) NULL,
  to_status VARCHAR(32) NOT NULL,
  reason VARCHAR(500) NULL,
  changed_by CHAR(36) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX idx_application_history(application_id,created_at),
  CONSTRAINT fk_application_history_application FOREIGN KEY(application_id) REFERENCES loan_applications(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS loan_eligibility_assessments (
  id CHAR(36) NOT NULL PRIMARY KEY,
  member_id VARCHAR(128) NULL,
  product_id CHAR(36) NULL,
  idempotency_key CHAR(36) NOT NULL,
  eligible BOOLEAN NOT NULL,
  repayment_percentage_bps INT UNSIGNED NULL,
  threshold_bps INT UNSIGNED NULL,
  reasons JSON NOT NULL,
  request_snapshot JSON NOT NULL,
  assessed_by CHAR(36) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_eligibility_idempotency(idempotency_key),
  INDEX idx_eligibility_member_created(member_id,created_at)
) ENGINE=InnoDB;
