ALTER TABLE normalized_loans ADD COLUMN IF NOT EXISTS penalty_outstanding_minor BIGINT UNSIGNED NOT NULL DEFAULT 0 AFTER total_outstanding_minor;

CREATE TABLE IF NOT EXISTS penalty_assessment_runs (
  id CHAR(36) PRIMARY KEY,
  run_reference VARCHAR(48) NOT NULL,
  assessment_date DATE NOT NULL,
  status ENUM('COMPLETED','FAILED') NOT NULL,
  idempotency_key CHAR(36) NOT NULL,
  request_hash CHAR(64) NOT NULL,
  assessed_loans INT UNSIGNED NOT NULL DEFAULT 0,
  posted_charges INT UNSIGNED NOT NULL DEFAULT 0,
  posted_amount_minor BIGINT UNSIGNED NOT NULL DEFAULT 0,
  skipped_count INT UNSIGNED NOT NULL DEFAULT 0,
  summary JSON NOT NULL,
  created_by CHAR(36) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_penalty_run_reference(run_reference),
  UNIQUE KEY uq_penalty_run_idempotency(idempotency_key),
  INDEX idx_penalty_run_date(assessment_date,created_at)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS loan_penalty_charges (
  id CHAR(36) PRIMARY KEY,
  penalty_reference VARCHAR(52) NOT NULL,
  run_id CHAR(36) NOT NULL,
  loan_id CHAR(36) NOT NULL,
  member_id CHAR(36) NOT NULL,
  schedule_id BIGINT UNSIGNED NOT NULL,
  policy_id CHAR(36) NOT NULL,
  policy_version INT UNSIGNED NOT NULL,
  assessment_date DATE NOT NULL,
  period_identifier VARCHAR(64) NOT NULL,
  eligible_assessment_date DATE NOT NULL,
  days_overdue INT UNSIGNED NOT NULL,
  calculation_method VARCHAR(48) NOT NULL,
  calculation_base_type VARCHAR(48) NOT NULL,
  base_amount_minor BIGINT UNSIGNED NOT NULL,
  rate_bps INT UNSIGNED NOT NULL DEFAULT 0,
  fixed_amount_minor BIGINT UNSIGNED NOT NULL DEFAULT 0,
  amount_before_cap_minor BIGINT UNSIGNED NOT NULL,
  cap_type VARCHAR(48) NOT NULL,
  cap_scope VARCHAR(32) NULL,
  cap_amount_minor BIGINT UNSIGNED NULL,
  amount_after_cap_minor BIGINT UNSIGNED NOT NULL,
  vat_minor BIGINT UNSIGNED NOT NULL DEFAULT 0,
  status ENUM('POSTED') NOT NULL DEFAULT 'POSTED',
  calculation_metadata JSON NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_penalty_reference(penalty_reference),
  UNIQUE KEY uq_penalty_interval(loan_id,schedule_id,policy_id,policy_version,period_identifier),
  INDEX idx_penalty_charge_loan(loan_id,assessment_date),
  INDEX idx_penalty_charge_policy(policy_id,policy_version,assessment_date),
  CONSTRAINT fk_penalty_charge_run FOREIGN KEY(run_id) REFERENCES penalty_assessment_runs(id),
  CONSTRAINT fk_penalty_charge_loan FOREIGN KEY(loan_id) REFERENCES normalized_loans(id),
  CONSTRAINT fk_penalty_charge_schedule FOREIGN KEY(schedule_id) REFERENCES loan_repayment_schedule(id),
  CONSTRAINT fk_penalty_charge_policy FOREIGN KEY(policy_id,policy_version) REFERENCES penalty_policy_versions(policy_id,version)
) ENGINE=InnoDB;
