CREATE TABLE IF NOT EXISTS loan_collection_cases (
 id CHAR(36) PRIMARY KEY,case_reference VARCHAR(52) NOT NULL,loan_id CHAR(36) NOT NULL,member_id CHAR(36) NOT NULL,
 status ENUM('OPEN','IN_PROGRESS','PROMISE_TO_PAY','MONITORING','RESOLVED','CLOSED') NOT NULL DEFAULT 'OPEN',assigned_officer_id CHAR(36) NULL,
 opened_date DATE NOT NULL,priority ENUM('LOW','NORMAL','HIGH','URGENT') NOT NULL DEFAULT 'NORMAL',reason VARCHAR(500) NOT NULL,next_follow_up_date DATE NULL,notes VARCHAR(5000) NOT NULL,
 resolution_reason VARCHAR(1000) NULL,record_version INT UNSIGNED NOT NULL DEFAULT 1,created_by CHAR(36) NOT NULL,updated_by CHAR(36) NOT NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
 active_loan_id CHAR(36) GENERATED ALWAYS AS(CASE WHEN status IN('OPEN','IN_PROGRESS','PROMISE_TO_PAY','MONITORING') THEN loan_id ELSE NULL END) STORED,
 UNIQUE KEY uq_collection_case_reference(case_reference),UNIQUE KEY uq_collection_active_loan(active_loan_id),INDEX idx_collection_case_queue(status,assigned_officer_id,next_follow_up_date),INDEX idx_collection_case_member(member_id,created_at),CONSTRAINT fk_collection_case_loan FOREIGN KEY(loan_id) REFERENCES normalized_loans(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS loan_collection_case_history (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,case_id CHAR(36) NOT NULL,from_status VARCHAR(32) NULL,to_status VARCHAR(32) NOT NULL,reason VARCHAR(1000) NOT NULL,changed_by CHAR(36) NOT NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),INDEX idx_collection_case_history(case_id,created_at),CONSTRAINT fk_collection_history_case FOREIGN KEY(case_id) REFERENCES loan_collection_cases(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS loan_collection_assignments (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,case_id CHAR(36) NOT NULL,previous_officer_id CHAR(36) NULL,new_officer_id CHAR(36) NOT NULL,reason VARCHAR(1000) NOT NULL,assigned_by CHAR(36) NOT NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),INDEX idx_collection_assignment_case(case_id,created_at),INDEX idx_collection_assignment_officer(new_officer_id,created_at),CONSTRAINT fk_collection_assignment_case FOREIGN KEY(case_id) REFERENCES loan_collection_cases(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS loan_collection_actions (
 id CHAR(36) PRIMARY KEY,action_reference VARCHAR(52) NOT NULL,case_id CHAR(36) NOT NULL,loan_id CHAR(36) NOT NULL,member_id CHAR(36) NOT NULL,action_type ENUM('PHONE_CALL','SMS_MANUAL','EMAIL_MANUAL','IN_PERSON_VISIT','LETTER','MEMBER_CONTACTED','NEXT_OF_KIN_CONTACTED','PROMISE_TO_PAY','NO_ANSWER','WRONG_CONTACT_DETAILS','FOLLOW_UP_SCHEDULED','OTHER') NOT NULL,action_at DATETIME NOT NULL,outcome VARCHAR(500) NOT NULL,notes VARCHAR(5000) NOT NULL,next_follow_up_date DATE NULL,recorded_by CHAR(36) NOT NULL,idempotency_key CHAR(36) NOT NULL,request_hash CHAR(64) NOT NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),UNIQUE KEY uq_collection_action_reference(action_reference),UNIQUE KEY uq_collection_action_idempotency(idempotency_key),INDEX idx_collection_action_case(case_id,action_at,created_at),CONSTRAINT fk_collection_action_case FOREIGN KEY(case_id) REFERENCES loan_collection_cases(id),CONSTRAINT fk_collection_action_loan FOREIGN KEY(loan_id) REFERENCES normalized_loans(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS loan_promises_to_pay (
 id CHAR(36) PRIMARY KEY,action_id CHAR(36) NOT NULL,case_id CHAR(36) NOT NULL,loan_id CHAR(36) NOT NULL,member_id CHAR(36) NOT NULL,promised_amount_minor BIGINT UNSIGNED NOT NULL,promised_payment_date DATE NOT NULL,stated_method VARCHAR(64) NULL,notes VARCHAR(5000) NOT NULL,status ENUM('PENDING','KEPT','PARTIALLY_KEPT','BROKEN','CANCELLED') NOT NULL DEFAULT 'PENDING',status_reason VARCHAR(1000) NULL,record_version INT UNSIGNED NOT NULL DEFAULT 1,created_by CHAR(36) NOT NULL,updated_by CHAR(36) NOT NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),UNIQUE KEY uq_collection_promise_action(action_id),INDEX idx_collection_promise_case(case_id,status,promised_payment_date),CONSTRAINT fk_collection_promise_action FOREIGN KEY(action_id) REFERENCES loan_collection_actions(id),CONSTRAINT fk_collection_promise_case FOREIGN KEY(case_id) REFERENCES loan_collection_cases(id),CONSTRAINT fk_collection_promise_loan FOREIGN KEY(loan_id) REFERENCES normalized_loans(id),CONSTRAINT chk_collection_promise_amount CHECK(promised_amount_minor>0)
) ENGINE=InnoDB;
